### ISSUE TITLE
Format particle data in Struct of Arrays and compare performance between SoA and AoS

### ISSUE THREAD

**Issue by Victor2266** [Victor2266/CPU-GPU-Fluid-Simulation-In-Unity#10]

**Comment by Victor2266** [comment]
we are starting by implementing the array of structs approach
![image](https://github.com/user-attachments/assets/2db5a656-7351-42e9-accc-80183a618291)

**Comment by DavisCheung** [comment]
Starting on this today. Refactor will be messy

**Comment by Victor2266** [comment]
Don't delete the array of structs so we can compare performance between them

**Comment by DavisCheung** [comment]
Can comment out and just have 2 branches, just don't merge them

**Comment by Victor2266** [comment]
I sent message on discord, if you comment them out it will be more annoying to swap between the scripts to compare performance, by having two scripts you can just enable/disable the gameobject that has the script you want to test with the press of a button

**Comment by Victor2266** [comment]
AoS has been implemented now to compare performance with SoA.
Also keep in mind that some changes to the regular simulation2D script have been made in the meantime which will have have to port over the the script we end up using

**Comment by DavisCheung** [comment]
Implemented AoS some time ago, looks like we are committing to AoS. Should we close this issue or are we expecting to go back to SoA in the future?

**Comment by Victor2266** [comment]
We never had SoA, we used discrete and separate arrays each of which had its own compute buffer.

In AoS we have a single array of particle structs which we send to the GPU in one compute buffer.
In SoA we would have a single struct containing all the arrays which we would send to the GPU in one compute buffer.

Here's a generated comparison:

**Separate Arrays & Compute Buffers:**
Pros:
- Better memory coalescing when accessing individual properties
- More flexible for updating specific properties without touching others
- Easier to debug as each property is isolated
- Can optimize memory layout for specific calculations

Cons:
- More overhead in managing multiple buffers
- More complex buffer synchronization
- Higher driver overhead from multiple buffer bindings

**Array of Particle Structs:**
Pros:
- More intuitive data organization
- Better cache coherency when accessing multiple properties of the same particle
- Simpler buffer management
- Closer to object-oriented thinking

Cons:
- May waste memory bandwidth when only accessing few properties
- Less optimal for operations that only need specific properties
- Potential for padding issues in struct alignment

**Single Struct of Arrays (SoA):**
Pros:
- Best of both worlds for memory layout
- Single buffer management
- Maintains good memory coalescing
- Reduced driver overhead

Cons:
- More complex to maintain
- Requires careful padding and alignment
- Can be harder to debug

**Considerations why SoA is probably the best for this application:**
- SPH calculations often need to access specific properties (like position) across many particles simultaneously
- Force calculations require multiple properties but in a structured way
- Modern GPUs perform best with coalesced memory access patterns
- Single buffer management reduces overhead

**With multiple fluid types, we will need to:**
- Access the fluid type flag frequently to determine behavior
- Look up fluid-type-specific properties (gravity, target density, etc.)
- Handle interactions between different fluid types
- Keep the frequently accessed fluid type flags in a tightly packed array for efficient memory access
- The fluid-type-specific properties could be stored in a separate constant buffer or structured buffer, accessed by the fluid type flag as an index

```
struct FluidSimDataSoA {
    // Frequently accessed together during spatial queries
    float3[] positions;
    float3[] velocities;
    uint[] fluidTypes;  // Could be packed into fewer bits if needed
    
    // Properties accessed during force calculation
    float3[] forces;
    float[] densities;
    float[] pressures;
    
    // Other arrays as needed
};
```

```
struct ParticleAoS {
    float3 position;
    float3 velocity;
    float3 force;
    float density;
    float pressure;
    int fluidType;
    // potentially padding here depending on alignment
};
```

```
//AoS implementation:
if (particles[i].fluidType == WATER) {
    // water specific calculations
}
```
```
//SoA Implementation:
if (fluidTypes[i] == WATER) {
    // work with positions[i], velocities[i] etc.
}
```

So for the particle data we should use SoA but,
For fluid type properties (like target density, gravity, etc.), we should use AoS. Here's why:
**Access Pattern Difference:**
- Unlike particle data where you're often processing many particles in parallel
- Fluid type properties are accessed more like a lookup table
- When you need a fluid type's properties, you typically need all or most of them at once
- Smaller number of elements (just number of fluid types vs number of particles)
