### ISSUE TITLE
Have each individual particle be simulated based on its own properties (enables active/inactive particles)

### ISSUE THREAD

**Issue by Victor2266** [Victor2266/CPU-GPU-Fluid-Simulation-In-Unity#13]

**Comment by Victor2266** [comment]
Related to AoS and SoA

**Comment by Victor2266** [comment]
- First get the compute shader and visual shader to skip fluid particles whose FluidType is 'Disabled'
- Then send the whole table of every fluid asset to the compute shader and have it simulate each particle according to its FluidType

**Comment by DavisCheung** [comment]
Tentatively done on branch "DavisStructRefactor".
FluidData parameters for ALL types is defaulted to the "water" we have on the level 1 scene.
For FluidData.fluidType == 0, every single Kernel will try to skip calculations if possible (although this might be problematic for hashing purposes).
