### ISSUE TITLE
Delete The Unused Branches

### ISSUE THREAD

**Issue by Victor2266** [Victor2266/CPU-GPU-Fluid-Simulation-In-Unity#37]
just delete unused branches to keep things organized I think all of them are either old or have served their purpose

**Comment by DavisCheung** [comment]
Killed a bunch of them using git commands.

**Comment by Victor2266** [comment]
the bottom two seem to be old and inactive
![image](https://github.com/user-attachments/assets/9e157c8c-942b-40c5-8c81-3255b42c5ef4)

**Comment by FriitzTM** [comment]
"Cameron-CPU-GPU-Proto1" can be deleted.

**Comment by Victor2266** [comment]
@FriitzTM I think you have to delete it, it wasn't letting me

**Comment by Victor2266** [comment]
It just let me delete it

**Comment by Victor2266** [comment]
I'll mark this as done and ask JJ to delete his branch if it's unused
